// O catálogo de temas, na ordem em que aparecem nas Preferências.
//
// Os do Lace (Atlas, Atlas Branco) são o visual neutro das ADRs 0005 e 0007.
// O Aurora Legacy traz a paleta da AURORA. Os outros seguem a paleta oficial
// de cada tema, conferida na fonte em 2026-10-04:
//
// | Tema                 | Fonte                                                        |
// |----------------------|--------------------------------------------------------------|
// | Aurora Legacy        | ../Zelda-main: css/base/brand_tokens.css, theme_variables.css, js/editor/monaco_editor.js, js/terminal/shell_terminal.js |
// | Dark/Light Modern    | microsoft/vscode, extensions/theme-defaults (dark_modern, light_modern, dark_plus, light_plus) e terminalColorRegistry.ts |
// | Monokai              | microsoft/vscode, extensions/theme-monokai                   |
// | Solarized Dark/Light | microsoft/vscode, extensions/theme-solarized-*              |
// | Dracula              | dracula/visual-studio-code, src/dracula.yml                  |
// | Gruvbox Dark/Light   | morhetz/gruvbox, colors/gruvbox.vim                          |
// | Nord                 | nordtheme/visual-studio-code, themes/nord-color-theme.json   |
// | One Dark Pro         | Binaryify/OneDark-Pro, themes/OneDark-Pro.json               |
// | Catppuccin Mocha     | catppuccin/palette, palette.json                             |
// | Tokyo Night          | enkia/tokyo-night-vscode-theme                               |
//
// A sintaxe e os terminais usam as cores do tema como vieram; o contraste
// baixo que alguns têm de propósito (o comentário do Nord, os tons do
// Solarized) fica. A exceção é o apagado dos consoles, que terminalTheme
// (console/consoles.ts) clareia até 3:1. A interface do Studio tem menos
// camadas que a do VS Code, então os fundos foram escolhidos entre as cores
// do próprio tema, e onde faltava um tom (texto secundário, borda forte) ele
// sai de `mix` entre duas cores do tema.

import { alpha, mix, type Theme } from './model';

/**
 * O azul do CERN: Pantone 286 C, #0033A0 (R0 G51 B160), com os quatro tons
 * da paleta oficial, conforme design-guidelines.web.cern.ch/guidelines/colours.
 * Sobre o fundo escuro o #0033A0 quase some numa linha fina, então linhas e
 * textos usam os tons claros, e o #0033A0 fica para preenchimentos (ADR 0007).
 */
const CERN_BLUE = {
  base: '#0033A0',
  t80: '#385CB4',
  t60: '#6B84C5',
  t40: '#9BAEDB',
  t20: '#CDD6ED',
};

// Lace -------------------------------------------------------------------

/** O padrão: cinzas sem matiz, cor só com função, azul do CERN nos detalhes.
 * A sintaxe usa poucos tons foscos (aço, sálvia, areia, argila). */
const atlas: Theme = {
  id: 'atlas',
  name: 'Atlas',
  scheme: 'dark',
  pair: 'atlas-light',
  ui: {
    bg0: '#161616',
    bg1: '#1B1B1B',
    bg2: '#1F1F1F',
    bg3: '#262626',
    bg4: '#2E2E2E',
    bgEditor: '#1B1B1B',
    border: '#2A2A2A',
    borderStrong: '#3A3A3A',
    text0: '#E4E4E4',
    text1: '#B8B8B8',
    text2: '#8C8C8C',
    text3: '#5E5E5E',
    brand: CERN_BLUE.t60,
    brandText: CERN_BLUE.t40,
    brandFill: CERN_BLUE.base,
    brandFillHover: CERN_BLUE.t80,
    brandContrast: '#FFFFFF',
    ok: '#7FB07F',
    warn: '#CFA55A',
    error: '#D9685F',
    info: '#8FA3BF',
  },
  syntax: {
    fg: '#D4D4D4',
    comment: '#6A6A6A',
    keyword: '#8FA1BA',
    control: '#BE8A73',
    type: '#9DB08A',
    func: '#9DB08A',
    number: '#C2A06C',
    string: '#BE8A73',
    constant: '#C2A06C',
    variable: '#A6B5CA',
    tag: '#8FA1BA',
    operator: '#A0A0A0',
    delimiter: '#A0A0A0',
    directive: '#C8C8C8',
  },
  editor: {
    selection: alpha(CERN_BLUE.base, 0.55),
    selectionInactive: alpha(CERN_BLUE.base, 0.3),
    lineHighlight: '#222222',
    lineNumber: '#4A4A4A',
    lineNumberActive: '#A0A0A0',
    cursor: '#E4E4E4',
    findMatch: '#5A5A5A',
    findMatchHighlight: '#3A3A3A',
    indentGuide: '#262626',
    indentGuideActive: '#3A3A3A',
  },
  terminal: {
    foreground: '#C8C8C8',
    selection: alpha(CERN_BLUE.base, 0.55),
    black: '#161616',
    red: '#D9685F',
    green: '#7FB07F',
    yellow: '#CFA55A',
    blue: '#8FA1BA',
    magenta: '#A9A2B8',
    cyan: '#8FA3BF',
    white: '#D4D4D4',
    brightBlack: '#6A6A6A',
    brightRed: '#E3857D',
    brightGreen: '#97C297',
    brightYellow: '#DBB878',
    brightBlue: '#A6B5CA',
    brightMagenta: '#BDB7CA',
    brightCyan: '#A6B6CC',
    brightWhite: '#EEEEEE',
  },
};

/** O Atlas claro. O #0033A0 serve para linhas, texto e preenchimento. */
const atlasLight: Theme = {
  id: 'atlas-light',
  name: 'Atlas Branco',
  scheme: 'light',
  pair: 'atlas',
  ui: {
    bg0: '#ECECEC',
    bg1: '#F4F4F4',
    bg2: '#FAFAFA',
    bg3: '#ECECEC',
    bg4: '#E2E2E2',
    bgEditor: '#FFFFFF',
    border: '#DEDEDE',
    borderStrong: '#C8C8C8',
    text0: '#1C1C1C',
    text1: '#3E3E3E',
    text2: '#6B6B6B',
    text3: '#9E9E9E',
    brand: CERN_BLUE.base,
    brandText: CERN_BLUE.base,
    brandFill: CERN_BLUE.base,
    brandFillHover: CERN_BLUE.t80,
    brandContrast: '#FFFFFF',
    ok: '#3F7D3F',
    warn: '#946414',
    error: '#B5443C',
    info: '#4B6386',
  },
  syntax: {
    fg: '#1C1C1C',
    comment: '#8C8C8C',
    keyword: '#3E5A80',
    control: '#98482F',
    type: '#4E6B36',
    func: '#4E6B36',
    number: '#85601E',
    string: '#98482F',
    constant: '#85601E',
    variable: '#4E6C96',
    tag: '#3E5A80',
    operator: '#555555',
    delimiter: '#555555',
    directive: '#333333',
  },
  editor: {
    selection: CERN_BLUE.t20,
    selectionInactive: alpha(CERN_BLUE.t20, 0.6),
    lineHighlight: '#F4F4F4',
    lineNumber: '#B0B0B0',
    lineNumberActive: '#3E3E3E',
    cursor: '#1C1C1C',
    findMatch: '#D0D0D0',
    findMatchHighlight: '#E6E6E6',
    indentGuide: '#ECECEC',
    indentGuideActive: '#C8C8C8',
  },
  terminal: {
    foreground: '#2B2B2B',
    selection: CERN_BLUE.t20,
    black: '#1C1C1C',
    red: '#B5443C',
    green: '#3F7D3F',
    yellow: '#946414',
    blue: '#3E5A80',
    magenta: '#5E5670',
    cyan: '#4B6386',
    white: '#3E3E3E',
    brightBlack: '#8C8C8C',
    brightRed: '#C65A52',
    brightGreen: '#4F914F',
    brightYellow: '#A8761E',
    brightBlue: '#4E6C96',
    brightMagenta: '#70688A',
    brightCyan: '#5B7499',
    brightWhite: '#1C1C1C',
  },
};

/**
 * A paleta da AURORA: céu noturno (#0A0D14), violeta #8E83E8 de destaque e
 * menta, ciano, roxo e rosa de apoio. A sintaxe é a do tema `cmm-dark` da
 * AURORA, levada aos tokens das gramáticas do Studio.
 */
const auroraLegacy: Theme = {
  id: 'aurora-legacy',
  name: 'Aurora Legacy',
  scheme: 'dark',
  ui: {
    bg0: '#0F131C',
    bg1: '#0F131C',
    bg2: '#151A25',
    bg3: '#1B2130',
    bg4: '#2A3040',
    bgEditor: '#0A0D14',
    border: '#1F2532',
    borderStrong: '#2A3040',
    text0: '#E8ECF3',
    text1: '#9CA1AE',
    text2: '#6A6F7C',
    text3: '#3F434E',
    brand: '#8E83E8',
    brandText: '#A89EF0',
    brandFill: '#6E63C8',
    brandFillHover: '#8E83E8',
    brandContrast: '#FFFFFF',
    brandSoft: '#8E83E82E',
    ok: '#5DD4A8',
    warn: '#E8B86C',
    error: '#E26C6C',
    info: '#5BB8E8',
    hover: '#FFFFFF09',
    overlay: '#06080CB8',
    shadowPop: '0 6px 18px #00000073',
  },
  syntax: {
    fg: '#E8ECF3',
    comment: '#6A6F7C',
    keyword: '#8E83E8',
    control: '#E8B86C',
    type: '#8E83E8',
    func: '#5BB8E8',
    number: '#5FE0B0',
    string: '#E68FB8',
    constant: '#E8B86C',
    variable: '#4FD3C2',
    tag: '#8E83E8',
    operator: '#9CA1AE',
    delimiter: '#9CA1AE',
    directive: '#B98AE0',
    style: { keyword: 'bold', type: 'bold', func: 'bold', constant: 'bold', directive: '' },
  },
  rules: [
    { token: 'dirac.bracket.cmm', foreground: 'A89EF0', fontStyle: 'bold' },
    { token: 'dirac.bar.cmm', foreground: 'A89EF0', fontStyle: 'bold' },
    { token: 'dirac.special.cmm', foreground: 'B98AE0', fontStyle: 'bold' },
    { token: 'number.imaginary.cmm', foreground: 'BD93F9', fontStyle: 'bold' },
    { token: 'operator.shift.arithmetic.cmm', foreground: 'A89EF0', fontStyle: 'bold' },
    { token: 'label.asm', foreground: 'A89EF0', fontStyle: 'italic' },
  ],
  editor: {
    selection: '#8E83E830',
    selectionInactive: '#8E83E820',
    lineHighlight: '#0F131C',
    lineNumber: '#3F434E',
    lineNumberActive: '#A89EF0',
    cursor: '#8E83E8',
    findMatch: '#8E83E866',
    findMatchHighlight: '#8E83E833',
    indentGuide: '#161A23',
    indentGuideActive: '#8E83E8',
    bracketMatch: '#8E83E833',
    bracketMatchBorder: '#8E83E8',
    brackets: ['#5FE0B0', '#5BB8E8', '#8E83E8', '#B98AE0', '#E68FB8', '#4FD3C2'],
  },
  terminal: {
    foreground: '#E8ECF3',
    selection: '#8E83E859',
    black: '#11131C',
    red: '#E26C6C',
    green: '#5FE0B0',
    yellow: '#E8C97D',
    blue: '#5BB8E8',
    magenta: '#B58AE8',
    cyan: '#4FD3C2',
    white: '#C5C9D6',
    brightBlack: '#5A6072',
    brightRed: '#FF8A8A',
    brightGreen: '#7FF0C6',
    brightYellow: '#FFE0A0',
    brightBlue: '#8CD0FF',
    brightMagenta: '#D0B0FF',
    brightCyan: '#7FEFE0',
    brightWhite: '#FFFFFF',
  },
};

// Os padrões do VS Code ---------------------------------------------------

const VSCODE_DARK_ANSI = {
  black: '#000000',
  red: '#CD3131',
  green: '#0DBC79',
  yellow: '#E5E510',
  blue: '#2472C8',
  magenta: '#BC3FBC',
  cyan: '#11A8CD',
  white: '#E5E5E5',
  brightBlack: '#666666',
  brightRed: '#F14C4C',
  brightGreen: '#23D18B',
  brightYellow: '#F5F543',
  brightBlue: '#3B8EEA',
  brightMagenta: '#D670D6',
  brightCyan: '#29B8DB',
  brightWhite: '#E5E5E5',
};

/** O tema padrão do VS Code desde 2023, com a sintaxe do Dark+. */
const darkModern: Theme = {
  id: 'dark-modern',
  name: 'Dark Modern',
  scheme: 'dark',
  pair: 'light-modern',
  ui: {
    bg0: '#181818',
    bg1: '#181818',
    bg2: '#202020',
    bg3: '#313131',
    bg4: '#3C3C3C',
    bgEditor: '#1F1F1F',
    border: '#2B2B2B',
    borderStrong: '#3C3C3C',
    text0: '#FFFFFF',
    text1: '#CCCCCC',
    text2: '#9D9D9D',
    text3: '#6E7681',
    brand: '#0078D4',
    brandText: '#4DAAFC',
    brandFill: '#0078D4',
    brandFillHover: '#026EC1',
    brandContrast: '#FFFFFF',
    ok: '#2EA043',
    warn: '#CCA700',
    error: '#F85149',
    info: '#3794FF',
  },
  syntax: {
    fg: '#CCCCCC',
    comment: '#6A9955',
    keyword: '#569CD6',
    control: '#C586C0',
    type: '#4EC9B0',
    func: '#DCDCAA',
    number: '#B5CEA8',
    string: '#CE9178',
    constant: '#4FC1FF',
    variable: '#9CDCFE',
    tag: '#569CD6',
    operator: '#D4D4D4',
    delimiter: '#D4D4D4',
    directive: '#569CD6',
    style: { comment: '', directive: '' },
  },
  editor: {
    selection: '#264F78',
    selectionInactive: '#3A3D41',
    lineHighlight: '#00000000',
    lineHighlightBorder: '#282828',
    lineNumber: '#6E7681',
    lineNumberActive: '#CCCCCC',
    cursor: '#AEAFAD',
    findMatch: '#9E6A03',
    findMatchHighlight: '#EA5C0055',
    indentGuide: '#404040',
    indentGuideActive: '#707070',
    bracketMatch: '#0064001A',
    bracketMatchBorder: '#888888',
    brackets: ['#FFD700', '#DA70D6', '#179FFF'],
  },
  terminal: { foreground: '#CCCCCC', selection: '#264F78', ...VSCODE_DARK_ANSI },
};

/** O par claro do Dark Modern, com a sintaxe do Light+. */
const lightModern: Theme = {
  id: 'light-modern',
  name: 'Light Modern',
  scheme: 'light',
  pair: 'dark-modern',
  ui: {
    bg0: '#F8F8F8',
    bg1: '#F8F8F8',
    bg2: '#FFFFFF',
    bg3: '#E5E5E5',
    bg4: '#CCCCCC',
    bgEditor: '#FFFFFF',
    border: '#E5E5E5',
    borderStrong: '#CECECE',
    text0: '#1F1F1F',
    text1: '#3B3B3B',
    text2: '#616161',
    text3: '#8B949E',
    brand: '#005FB8',
    brandText: '#005FB8',
    brandFill: '#005FB8',
    brandFillHover: '#0258A8',
    brandContrast: '#FFFFFF',
    ok: '#2EA043',
    warn: '#BF8803',
    error: '#E51400',
    info: '#1A85FF',
  },
  syntax: {
    fg: '#3B3B3B',
    comment: '#008000',
    keyword: '#0000FF',
    control: '#AF00DB',
    type: '#267F99',
    func: '#795E26',
    number: '#098658',
    string: '#A31515',
    constant: '#0070C1',
    variable: '#0451A5',
    tag: '#800000',
    operator: '#3B3B3B',
    delimiter: '#3B3B3B',
    directive: '#0000FF',
    style: { comment: '', directive: '' },
  },
  editor: {
    selection: '#ADD6FF',
    selectionInactive: '#E5EBF1',
    lineHighlight: '#00000000',
    lineHighlightBorder: '#EEEEEE',
    lineNumber: '#6E7681',
    lineNumberActive: '#171184',
    cursor: '#000000',
    findMatch: '#A8AC94',
    findMatchHighlight: '#EA5C0055',
    indentGuide: '#D3D3D3',
    indentGuideActive: '#939393',
    bracketMatch: '#0064001A',
    bracketMatchBorder: '#B9B9B9',
    brackets: ['#0431FA', '#319331', '#7B3814'],
  },
  terminal: {
    foreground: '#3B3B3B',
    selection: '#ADD6FF',
    black: '#000000',
    red: '#CD3131',
    green: '#107C10',
    yellow: '#949800',
    blue: '#0451A5',
    magenta: '#BC05BC',
    cyan: '#0598BC',
    white: '#555555',
    brightBlack: '#666666',
    brightRed: '#F14C4C',
    brightGreen: '#14CE14',
    brightYellow: '#B5BA00',
    brightBlue: '#3B8EEA',
    brightMagenta: '#D670D6',
    brightCyan: '#29B8DB',
    brightWhite: '#A5A5A5',
  },
};

// Populares ---------------------------------------------------------------

const DRACULA = {
  bg: '#282A36',
  fg: '#F8F8F2',
  selection: '#44475A',
  comment: '#6272A4',
  cyan: '#8BE9FD',
  green: '#50FA7B',
  orange: '#FFB86C',
  pink: '#FF79C6',
  purple: '#BD93F9',
  red: '#FF5555',
  yellow: '#F1FA8C',
  bgLighter: '#424450',
  bgLight: '#343746',
  bgDark: '#21222C',
  bgDarker: '#191A21',
};

const dracula: Theme = {
  id: 'dracula',
  name: 'Dracula',
  scheme: 'dark',
  ui: {
    bg0: DRACULA.bgDarker,
    bg1: DRACULA.bgDark,
    bg2: DRACULA.bgDark,
    bg3: DRACULA.bgLight,
    bg4: DRACULA.selection,
    bgEditor: DRACULA.bg,
    border: DRACULA.bgDarker,
    borderStrong: DRACULA.selection,
    text0: DRACULA.fg,
    text1: mix(DRACULA.fg, DRACULA.bg, 0.2),
    text2: mix(DRACULA.fg, DRACULA.bg, 0.45),
    text3: DRACULA.comment,
    brand: DRACULA.purple,
    brandText: DRACULA.purple,
    brandFill: DRACULA.purple,
    brandFillHover: mix(DRACULA.purple, DRACULA.fg, 0.25),
    brandContrast: DRACULA.bg,
    brandSoft: '#BD93F933',
    ok: DRACULA.green,
    warn: DRACULA.orange,
    error: DRACULA.red,
    info: DRACULA.cyan,
  },
  syntax: {
    fg: DRACULA.fg,
    comment: DRACULA.comment,
    keyword: DRACULA.pink,
    control: DRACULA.pink,
    type: DRACULA.cyan,
    func: DRACULA.green,
    number: DRACULA.purple,
    string: DRACULA.yellow,
    constant: DRACULA.purple,
    variable: DRACULA.cyan,
    tag: DRACULA.pink,
    operator: DRACULA.pink,
    delimiter: DRACULA.fg,
    directive: DRACULA.pink,
    style: { type: 'italic', directive: '' },
  },
  editor: {
    selection: DRACULA.selection,
    lineHighlight: '#00000000',
    lineHighlightBorder: DRACULA.selection,
    lineNumber: DRACULA.comment,
    lineNumberActive: DRACULA.fg,
    cursor: DRACULA.fg,
    findMatch: '#FFB86C80',
    findMatchHighlight: '#FFFFFF40',
    indentGuide: '#FFFFFF1A',
    indentGuideActive: '#FFFFFF45',
    brackets: [DRACULA.fg, DRACULA.pink, DRACULA.cyan, DRACULA.green, DRACULA.purple, DRACULA.orange],
  },
  terminal: {
    foreground: DRACULA.fg,
    selection: DRACULA.selection,
    black: '#21222C',
    red: '#FF5555',
    green: '#50FA7B',
    yellow: '#F1FA8C',
    blue: '#BD93F9',
    magenta: '#FF79C6',
    cyan: '#8BE9FD',
    white: '#F8F8F2',
    brightBlack: '#6272A4',
    brightRed: '#FF6E6E',
    brightGreen: '#69FF94',
    brightYellow: '#FFFFA5',
    brightBlue: '#D6ACFF',
    brightMagenta: '#FF92DF',
    brightCyan: '#A4FFFF',
    brightWhite: '#FFFFFF',
  },
};

/** As cores do Gruvbox (morhetz). No escuro a sintaxe usa as `bright_*`; no
 * claro, as `faded_*`; os terminais, as `neutral_*` e as do esquema. */
const GRUVBOX = {
  dark0Hard: '#1D2021',
  dark0: '#282828',
  dark0Soft: '#32302F',
  dark1: '#3C3836',
  dark2: '#504945',
  dark3: '#665C54',
  dark4: '#7C6F64',
  gray: '#928374',
  light0Hard: '#F9F5D7',
  light0: '#FBF1C7',
  light0Soft: '#F2E5BC',
  light1: '#EBDBB2',
  light2: '#D5C4A1',
  light3: '#BDAE93',
  light4: '#A89984',
  brightRed: '#FB4934',
  brightGreen: '#B8BB26',
  brightYellow: '#FABD2F',
  brightBlue: '#83A598',
  brightPurple: '#D3869B',
  brightAqua: '#8EC07C',
  brightOrange: '#FE8019',
  neutralRed: '#CC241D',
  neutralGreen: '#98971A',
  neutralYellow: '#D79921',
  neutralBlue: '#458588',
  neutralPurple: '#B16286',
  neutralAqua: '#689D6A',
  neutralOrange: '#D65D0E',
  fadedRed: '#9D0006',
  fadedGreen: '#79740E',
  fadedYellow: '#B57614',
  fadedBlue: '#076678',
  fadedPurple: '#8F3F71',
  fadedAqua: '#427B58',
  fadedOrange: '#AF3A03',
};

const GRUVBOX_BRACKETS = [
  GRUVBOX.neutralPurple,
  GRUVBOX.neutralBlue,
  GRUVBOX.neutralAqua,
  GRUVBOX.neutralGreen,
  GRUVBOX.neutralYellow,
  GRUVBOX.neutralOrange,
];

const gruvboxDark: Theme = {
  id: 'gruvbox-dark',
  name: 'Gruvbox Dark',
  scheme: 'dark',
  pair: 'gruvbox-light',
  ui: {
    bg0: GRUVBOX.dark0Hard,
    bg1: GRUVBOX.dark0,
    bg2: GRUVBOX.dark0Soft,
    bg3: GRUVBOX.dark1,
    bg4: GRUVBOX.dark2,
    bgEditor: GRUVBOX.dark0,
    border: GRUVBOX.dark1,
    borderStrong: GRUVBOX.dark2,
    text0: GRUVBOX.light0,
    text1: GRUVBOX.light1,
    text2: GRUVBOX.light4,
    text3: GRUVBOX.dark4,
    brand: GRUVBOX.brightBlue,
    brandText: GRUVBOX.brightBlue,
    brandFill: GRUVBOX.neutralBlue,
    brandFillHover: mix(GRUVBOX.neutralBlue, GRUVBOX.brightBlue, 0.2),
    brandContrast: GRUVBOX.light0,
    ok: GRUVBOX.brightGreen,
    warn: GRUVBOX.brightYellow,
    error: GRUVBOX.brightRed,
    info: GRUVBOX.brightBlue,
  },
  syntax: {
    fg: GRUVBOX.light1,
    comment: GRUVBOX.gray,
    keyword: GRUVBOX.brightRed,
    control: GRUVBOX.brightRed,
    type: GRUVBOX.brightYellow,
    func: GRUVBOX.brightOrange,
    number: GRUVBOX.brightPurple,
    string: GRUVBOX.brightGreen,
    constant: GRUVBOX.brightPurple,
    variable: GRUVBOX.brightBlue,
    tag: GRUVBOX.brightBlue,
    operator: GRUVBOX.light1,
    delimiter: GRUVBOX.light4,
    directive: GRUVBOX.brightAqua,
    style: { directive: '' },
  },
  editor: {
    selection: GRUVBOX.dark2,
    lineHighlight: GRUVBOX.dark1,
    lineNumber: GRUVBOX.dark4,
    lineNumberActive: GRUVBOX.brightYellow,
    cursor: GRUVBOX.light1,
    findMatch: '#FABD2F66',
    findMatchHighlight: '#FABD2F2E',
    indentGuide: GRUVBOX.dark1,
    indentGuideActive: GRUVBOX.dark3,
    brackets: GRUVBOX_BRACKETS,
  },
  terminal: {
    foreground: GRUVBOX.light1,
    selection: GRUVBOX.dark2,
    black: GRUVBOX.dark0,
    red: GRUVBOX.neutralRed,
    green: GRUVBOX.neutralGreen,
    yellow: GRUVBOX.neutralYellow,
    blue: GRUVBOX.neutralBlue,
    magenta: GRUVBOX.neutralPurple,
    cyan: GRUVBOX.neutralAqua,
    white: GRUVBOX.light4,
    brightBlack: GRUVBOX.gray,
    brightRed: GRUVBOX.brightRed,
    brightGreen: GRUVBOX.brightGreen,
    brightYellow: GRUVBOX.brightYellow,
    brightBlue: GRUVBOX.brightBlue,
    brightMagenta: GRUVBOX.brightPurple,
    brightCyan: GRUVBOX.brightAqua,
    brightWhite: GRUVBOX.light1,
  },
};

const gruvboxLight: Theme = {
  id: 'gruvbox-light',
  name: 'Gruvbox Light',
  scheme: 'light',
  pair: 'gruvbox-dark',
  ui: {
    bg0: GRUVBOX.light1,
    bg1: GRUVBOX.light0Soft,
    bg2: GRUVBOX.light0Hard,
    bg3: GRUVBOX.light1,
    bg4: GRUVBOX.light2,
    bgEditor: GRUVBOX.light0,
    border: GRUVBOX.light2,
    borderStrong: GRUVBOX.light3,
    text0: GRUVBOX.dark0,
    text1: GRUVBOX.dark1,
    text2: GRUVBOX.dark4,
    text3: GRUVBOX.light4,
    brand: GRUVBOX.fadedBlue,
    brandText: GRUVBOX.fadedBlue,
    brandFill: GRUVBOX.fadedBlue,
    brandFillHover: GRUVBOX.neutralBlue,
    brandContrast: GRUVBOX.light0,
    ok: GRUVBOX.fadedGreen,
    warn: GRUVBOX.fadedYellow,
    error: GRUVBOX.fadedRed,
    info: GRUVBOX.fadedBlue,
  },
  syntax: {
    fg: GRUVBOX.dark1,
    comment: GRUVBOX.gray,
    keyword: GRUVBOX.fadedRed,
    control: GRUVBOX.fadedRed,
    type: GRUVBOX.fadedYellow,
    func: GRUVBOX.fadedOrange,
    number: GRUVBOX.fadedPurple,
    string: GRUVBOX.fadedGreen,
    constant: GRUVBOX.fadedPurple,
    variable: GRUVBOX.fadedBlue,
    tag: GRUVBOX.fadedBlue,
    operator: GRUVBOX.dark1,
    delimiter: GRUVBOX.dark4,
    directive: GRUVBOX.fadedAqua,
    style: { directive: '' },
  },
  editor: {
    selection: GRUVBOX.light2,
    lineHighlight: GRUVBOX.light0Soft,
    lineNumber: GRUVBOX.light4,
    lineNumberActive: GRUVBOX.fadedYellow,
    cursor: GRUVBOX.dark1,
    findMatch: '#B5761466',
    findMatchHighlight: '#B576142E',
    indentGuide: GRUVBOX.light1,
    indentGuideActive: GRUVBOX.light3,
    brackets: GRUVBOX_BRACKETS,
  },
  terminal: {
    foreground: GRUVBOX.dark1,
    selection: GRUVBOX.light2,
    black: GRUVBOX.light0,
    red: GRUVBOX.neutralRed,
    green: GRUVBOX.neutralGreen,
    yellow: GRUVBOX.neutralYellow,
    blue: GRUVBOX.neutralBlue,
    magenta: GRUVBOX.neutralPurple,
    cyan: GRUVBOX.neutralAqua,
    white: GRUVBOX.dark4,
    brightBlack: GRUVBOX.gray,
    brightRed: GRUVBOX.fadedRed,
    brightGreen: GRUVBOX.fadedGreen,
    brightYellow: GRUVBOX.fadedYellow,
    brightBlue: GRUVBOX.fadedBlue,
    brightMagenta: GRUVBOX.fadedPurple,
    brightCyan: GRUVBOX.fadedAqua,
    brightWhite: GRUVBOX.dark1,
  },
};

/** O Monokai do VS Code. O destaque é o amarelo das strings, como no Monokai Pro. */
const monokai: Theme = {
  id: 'monokai',
  name: 'Monokai',
  scheme: 'dark',
  ui: {
    bg0: '#1E1F1C',
    bg1: '#1E1F1C',
    bg2: '#272822',
    bg3: '#414339',
    bg4: '#75715E',
    bgEditor: '#272822',
    border: '#34352F',
    borderStrong: '#414339',
    text0: '#F8F8F2',
    text1: '#CFCFC2',
    text2: '#90908A',
    text3: '#75715E',
    brand: '#E6DB74',
    brandText: '#E6DB74',
    brandFill: '#E6DB74',
    brandFillHover: mix('#E6DB74', '#F8F8F2', 0.3),
    brandContrast: '#272822',
    brandSoft: '#E6DB7426',
    ok: '#A6E22E',
    warn: '#FD971F',
    error: '#F92672',
    info: '#66D9EF',
  },
  syntax: {
    fg: '#F8F8F2',
    comment: '#88846F',
    keyword: '#F92672',
    control: '#F92672',
    type: '#66D9EF',
    func: '#66D9EF',
    number: '#AE81FF',
    string: '#E6DB74',
    constant: '#AE81FF',
    variable: '#FD971F',
    tag: '#F92672',
    operator: '#F92672',
    delimiter: '#F8F8F2',
    directive: '#F92672',
    style: { comment: '', type: 'italic', directive: '' },
  },
  editor: {
    selection: '#878B9180',
    lineHighlight: '#3E3D32',
    lineNumber: '#90908A',
    lineNumberActive: '#C2C2BF',
    cursor: '#F8F8F0',
    findMatch: '#E6DB7466',
    findMatchHighlight: '#E6DB7428',
    indentGuide: '#464741',
    indentGuideActive: '#767771',
  },
  terminal: {
    foreground: '#F8F8F2',
    selection: '#878B9180',
    black: '#333333',
    red: '#C4265E',
    green: '#86B42B',
    yellow: '#B3B42B',
    blue: '#6A7EC8',
    magenta: '#8C6BC8',
    cyan: '#56ADBC',
    white: '#E3E3DD',
    brightBlack: '#666666',
    brightRed: '#F92672',
    brightGreen: '#A6E22E',
    brightYellow: '#E2E22E',
    brightBlue: '#819AFF',
    brightMagenta: '#AE81FF',
    brightCyan: '#66D9EF',
    brightWhite: '#F8F8F2',
  },
};

const NORD = {
  n0: '#2E3440',
  n1: '#3B4252',
  n2: '#434C5E',
  n3: '#4C566A',
  n4: '#D8DEE9',
  n5: '#E5E9F0',
  n6: '#ECEFF4',
  n7: '#8FBCBB',
  n8: '#88C0D0',
  n9: '#81A1C1',
  n10: '#5E81AC',
  n11: '#BF616A',
  n12: '#D08770',
  n13: '#EBCB8B',
  n14: '#A3BE8C',
  n15: '#B48EAD',
  comment: '#616E88',
};

const nord: Theme = {
  id: 'nord',
  name: 'Nord',
  scheme: 'dark',
  ui: {
    bg0: mix(NORD.n0, '#000000', 0.12),
    bg1: NORD.n0,
    bg2: NORD.n1,
    bg3: NORD.n1,
    bg4: NORD.n2,
    bgEditor: NORD.n0,
    border: NORD.n1,
    borderStrong: NORD.n3,
    text0: NORD.n6,
    text1: NORD.n4,
    text2: mix(NORD.n4, NORD.n0, 0.35),
    text3: NORD.comment,
    brand: NORD.n8,
    brandText: NORD.n8,
    brandFill: NORD.n8,
    brandFillHover: NORD.n7,
    brandContrast: NORD.n0,
    brandSoft: '#88C0D033',
    ok: NORD.n14,
    warn: NORD.n13,
    error: NORD.n11,
    info: NORD.n9,
  },
  syntax: {
    fg: NORD.n4,
    comment: NORD.comment,
    keyword: NORD.n9,
    control: NORD.n9,
    type: NORD.n7,
    func: NORD.n8,
    number: NORD.n15,
    string: NORD.n14,
    constant: NORD.n12,
    variable: NORD.n7,
    tag: NORD.n9,
    operator: NORD.n9,
    delimiter: NORD.n6,
    directive: NORD.n10,
    style: { comment: '', directive: '' },
  },
  editor: {
    selection: '#434C5ECC',
    selectionInactive: '#434C5ECC',
    lineHighlight: NORD.n1,
    lineNumber: NORD.n3,
    lineNumberActive: NORD.n4,
    cursor: NORD.n4,
    findMatch: '#88C0D066',
    findMatchHighlight: '#88C0D033',
    indentGuide: '#434C5EB3',
    indentGuideActive: NORD.n3,
    bracketMatch: '#2E344000',
    bracketMatchBorder: NORD.n8,
    brackets: [NORD.n7, NORD.n8, NORD.n9, NORD.n10],
  },
  terminal: {
    foreground: NORD.n4,
    selection: '#434C5ECC',
    black: NORD.n1,
    red: NORD.n11,
    green: NORD.n14,
    yellow: NORD.n13,
    blue: NORD.n9,
    magenta: NORD.n15,
    cyan: NORD.n8,
    white: NORD.n5,
    brightBlack: NORD.n3,
    brightRed: NORD.n11,
    brightGreen: NORD.n14,
    brightYellow: NORD.n13,
    brightBlue: NORD.n9,
    brightMagenta: NORD.n15,
    brightCyan: NORD.n7,
    brightWhite: NORD.n6,
  },
};

const oneDark: Theme = {
  id: 'one-dark',
  name: 'One Dark Pro',
  scheme: 'dark',
  ui: {
    bg0: '#21252B',
    bg1: '#21252B',
    bg2: '#21252B',
    bg3: '#30333D',
    bg4: '#404754',
    bgEditor: '#282C34',
    border: '#181A1F',
    borderStrong: '#3E4452',
    text0: '#D7DAE0',
    text1: '#ABB2BF',
    text2: '#7F848E',
    text3: '#5C6370',
    brand: '#61AFEF',
    brandText: '#61AFEF',
    brandFill: '#4D78CC',
    brandFillHover: '#528BFF',
    brandContrast: '#FFFFFF',
    ok: '#98C379',
    warn: '#E5C07B',
    error: '#E06C75',
    info: '#61AFEF',
  },
  syntax: {
    fg: '#ABB2BF',
    comment: '#7F848E',
    keyword: '#C678DD',
    control: '#C678DD',
    type: '#E5C07B',
    func: '#56B6C2',
    number: '#D19A66',
    string: '#98C379',
    constant: '#D19A66',
    variable: '#E06C75',
    tag: '#E06C75',
    operator: '#ABB2BF',
    delimiter: '#ABB2BF',
    directive: '#C678DD',
    style: { directive: '' },
  },
  editor: {
    selection: '#67769660',
    selectionInactive: '#3A3F4B',
    lineHighlight: '#2C313C',
    lineNumber: '#495162',
    lineNumberActive: '#ABB2BF',
    cursor: '#528BFF',
    findMatch: '#D19A6644',
    findMatchHighlight: '#FFFFFF22',
    indentGuide: '#3B4048',
    indentGuideActive: '#C8C8C859',
    bracketMatch: '#515A6B',
    bracketMatchBorder: '#515A6B',
    brackets: ['#D19A66', '#C678DD', '#56B6C2'],
  },
  terminal: {
    foreground: '#ABB2BF',
    selection: '#ABB2BF30',
    black: '#3F4451',
    red: '#E05561',
    green: '#8CC265',
    yellow: '#D18F52',
    blue: '#4AA5F0',
    magenta: '#C162DE',
    cyan: '#42B3C2',
    white: '#D7DAE0',
    brightBlack: '#4F5666',
    brightRed: '#FF616E',
    brightGreen: '#A5E075',
    brightYellow: '#F0A45D',
    brightBlue: '#4DC4FF',
    brightMagenta: '#DE73FF',
    brightCyan: '#4CD1E0',
    brightWhite: '#E6E6E6',
  },
};

/** As cores do Solarized (Ethan Schoonover). */
const SOLARIZED = {
  base03: '#002B36',
  base02: '#073642',
  base01: '#586E75',
  base00: '#657B83',
  base0: '#839496',
  base1: '#93A1A1',
  base2: '#EEE8D5',
  base3: '#FDF6E3',
  yellow: '#B58900',
  orange: '#CB4B16',
  red: '#DC322F',
  magenta: '#D33682',
  violet: '#6C71C4',
  blue: '#268BD2',
  cyan: '#2AA198',
  green: '#859900',
};

const SOLARIZED_ANSI = {
  black: SOLARIZED.base02,
  red: SOLARIZED.red,
  green: SOLARIZED.green,
  yellow: SOLARIZED.yellow,
  blue: SOLARIZED.blue,
  magenta: SOLARIZED.magenta,
  cyan: SOLARIZED.cyan,
  white: SOLARIZED.base2,
  brightBlack: SOLARIZED.base03,
  brightRed: SOLARIZED.orange,
  brightGreen: SOLARIZED.base01,
  brightYellow: SOLARIZED.base00,
  brightBlue: SOLARIZED.base0,
  brightMagenta: SOLARIZED.violet,
  brightCyan: SOLARIZED.base1,
  brightWhite: SOLARIZED.base3,
};

const SOLARIZED_SYNTAX = {
  keyword: SOLARIZED.green,
  control: SOLARIZED.green,
  type: SOLARIZED.yellow,
  func: SOLARIZED.blue,
  number: SOLARIZED.magenta,
  string: SOLARIZED.cyan,
  constant: SOLARIZED.orange,
  variable: SOLARIZED.blue,
  tag: SOLARIZED.blue,
  operator: SOLARIZED.green,
  directive: SOLARIZED.orange,
  style: { directive: '' },
};

const solarizedDark: Theme = {
  id: 'solarized-dark',
  name: 'Solarized Dark',
  scheme: 'dark',
  pair: 'solarized-light',
  ui: {
    bg0: '#00212B',
    bg1: '#00212B',
    bg2: SOLARIZED.base02,
    bg3: '#003847',
    bg4: '#005A6F',
    bgEditor: SOLARIZED.base03,
    border: SOLARIZED.base02,
    borderStrong: mix(SOLARIZED.base01, SOLARIZED.base03, 0.4),
    text0: SOLARIZED.base1,
    text1: SOLARIZED.base0,
    text2: SOLARIZED.base00,
    text3: SOLARIZED.base01,
    brand: SOLARIZED.blue,
    brandText: SOLARIZED.blue,
    brandFill: SOLARIZED.blue,
    brandFillHover: mix(SOLARIZED.blue, SOLARIZED.base1, 0.25),
    brandContrast: SOLARIZED.base3,
    ok: SOLARIZED.green,
    warn: SOLARIZED.yellow,
    error: SOLARIZED.red,
    info: SOLARIZED.blue,
  },
  syntax: { fg: SOLARIZED.base0, comment: SOLARIZED.base01, delimiter: SOLARIZED.base0, ...SOLARIZED_SYNTAX },
  editor: {
    selection: '#274642',
    lineHighlight: SOLARIZED.base02,
    lineNumber: SOLARIZED.base01,
    lineNumberActive: SOLARIZED.base1,
    cursor: '#D30102',
    findMatch: '#B5890066',
    findMatchHighlight: '#B5890030',
    indentGuide: '#93A1A126',
    indentGuideActive: '#93A1A160',
    brackets: ['#CDCDCD', SOLARIZED.yellow, SOLARIZED.magenta],
  },
  terminal: { foreground: SOLARIZED.base0, selection: '#274642', ...SOLARIZED_ANSI },
};

const solarizedLight: Theme = {
  id: 'solarized-light',
  name: 'Solarized Light',
  scheme: 'light',
  pair: 'solarized-dark',
  ui: {
    bg0: SOLARIZED.base2,
    bg1: SOLARIZED.base2,
    bg2: SOLARIZED.base3,
    bg3: '#DDD6C1',
    bg4: '#D3CBB7',
    bgEditor: SOLARIZED.base3,
    border: '#DDD6C1',
    borderStrong: mix('#DDD6C1', SOLARIZED.base01, 0.25),
    text0: SOLARIZED.base02,
    text1: SOLARIZED.base01,
    text2: SOLARIZED.base00,
    text3: SOLARIZED.base1,
    brand: SOLARIZED.blue,
    brandText: SOLARIZED.blue,
    brandFill: SOLARIZED.blue,
    brandFillHover: mix(SOLARIZED.blue, SOLARIZED.base02, 0.2),
    brandContrast: SOLARIZED.base3,
    ok: SOLARIZED.green,
    warn: SOLARIZED.yellow,
    error: SOLARIZED.red,
    info: SOLARIZED.blue,
  },
  syntax: { fg: SOLARIZED.base00, comment: SOLARIZED.base1, delimiter: SOLARIZED.base00, ...SOLARIZED_SYNTAX },
  editor: {
    selection: '#DDD6C1',
    lineHighlight: SOLARIZED.base2,
    lineNumber: SOLARIZED.base1,
    lineNumberActive: '#567983',
    cursor: SOLARIZED.base00,
    findMatch: '#B5890055',
    findMatchHighlight: '#B5890028',
    indentGuide: '#586E7533',
    indentGuideActive: '#081E2566',
    brackets: [SOLARIZED.base01, SOLARIZED.yellow, SOLARIZED.magenta],
  },
  terminal: { foreground: SOLARIZED.base00, selection: '#DDD6C1', ...SOLARIZED_ANSI },
};

const MOCHA = {
  rosewater: '#F5E0DC',
  pink: '#F5C2E7',
  mauve: '#CBA6F7',
  red: '#F38BA8',
  maroon: '#EBA0AC',
  peach: '#FAB387',
  yellow: '#F9E2AF',
  green: '#A6E3A1',
  teal: '#94E2D5',
  sky: '#89DCEB',
  sapphire: '#74C7EC',
  blue: '#89B4FA',
  lavender: '#B4BEFE',
  text: '#CDD6F4',
  subtext1: '#BAC2DE',
  subtext0: '#A6ADC8',
  overlay2: '#9399B2',
  overlay1: '#7F849C',
  overlay0: '#6C7086',
  surface2: '#585B70',
  surface1: '#45475A',
  surface0: '#313244',
  base: '#1E1E2E',
  mantle: '#181825',
  crust: '#11111B',
};

const catppuccinMocha: Theme = {
  id: 'catppuccin-mocha',
  name: 'Catppuccin Mocha',
  scheme: 'dark',
  ui: {
    bg0: MOCHA.crust,
    bg1: MOCHA.mantle,
    bg2: MOCHA.mantle,
    bg3: MOCHA.surface0,
    bg4: MOCHA.surface1,
    bgEditor: MOCHA.base,
    border: MOCHA.surface0,
    borderStrong: MOCHA.surface1,
    text0: MOCHA.text,
    text1: MOCHA.subtext1,
    text2: MOCHA.subtext0,
    text3: MOCHA.overlay0,
    brand: MOCHA.mauve,
    brandText: MOCHA.mauve,
    brandFill: MOCHA.mauve,
    brandFillHover: MOCHA.lavender,
    brandContrast: MOCHA.crust,
    brandSoft: '#CBA6F733',
    ok: MOCHA.green,
    warn: MOCHA.yellow,
    error: MOCHA.red,
    info: MOCHA.blue,
  },
  syntax: {
    fg: MOCHA.text,
    comment: MOCHA.overlay2,
    keyword: MOCHA.mauve,
    control: MOCHA.mauve,
    type: MOCHA.yellow,
    func: MOCHA.blue,
    number: MOCHA.peach,
    string: MOCHA.green,
    constant: MOCHA.peach,
    variable: MOCHA.lavender,
    tag: MOCHA.blue,
    operator: MOCHA.sky,
    delimiter: MOCHA.overlay2,
    directive: MOCHA.pink,
    style: { directive: '' },
  },
  editor: {
    selection: '#9399B240',
    selectionInactive: '#9399B226',
    lineHighlight: '#CDD6F412',
    lineNumber: MOCHA.overlay1,
    lineNumberActive: MOCHA.lavender,
    cursor: MOCHA.rosewater,
    findMatch: '#FAB38766',
    findMatchHighlight: '#FAB38733',
    indentGuide: MOCHA.surface0,
    indentGuideActive: MOCHA.surface1,
    brackets: [MOCHA.red, MOCHA.peach, MOCHA.yellow, MOCHA.green, MOCHA.sapphire, MOCHA.mauve],
  },
  terminal: {
    foreground: MOCHA.text,
    selection: '#585B7080',
    black: MOCHA.surface1,
    red: MOCHA.red,
    green: MOCHA.green,
    yellow: MOCHA.yellow,
    blue: MOCHA.blue,
    magenta: MOCHA.pink,
    cyan: MOCHA.teal,
    white: MOCHA.subtext1,
    brightBlack: MOCHA.surface2,
    brightRed: MOCHA.red,
    brightGreen: MOCHA.green,
    brightYellow: MOCHA.yellow,
    brightBlue: MOCHA.blue,
    brightMagenta: MOCHA.pink,
    brightCyan: MOCHA.teal,
    brightWhite: MOCHA.subtext0,
  },
};

const tokyoNight: Theme = {
  id: 'tokyo-night',
  name: 'Tokyo Night',
  scheme: 'dark',
  ui: {
    bg0: '#16161E',
    bg1: '#16161E',
    bg2: '#16161E',
    bg3: '#202330',
    bg4: '#292E42',
    bgEditor: '#1A1B26',
    border: '#101014',
    borderStrong: '#292E42',
    text0: '#C0CAF5',
    text1: '#A9B1D6',
    text2: '#787C99',
    text3: '#565F89',
    brand: '#7AA2F7',
    brandText: '#7AA2F7',
    brandFill: '#3D59A1',
    brandFillHover: mix('#3D59A1', '#7AA2F7', 0.3),
    brandContrast: '#FFFFFF',
    ok: '#9ECE6A',
    warn: '#E0AF68',
    error: '#F7768E',
    info: '#7DCFFF',
  },
  syntax: {
    fg: '#A9B1D6',
    comment: '#565F89',
    keyword: '#BB9AF7',
    control: '#BB9AF7',
    type: '#0DB9D7',
    func: '#7AA2F7',
    number: '#FF9E64',
    string: '#9ECE6A',
    constant: '#FF9E64',
    variable: '#73DACA',
    tag: '#F7768E',
    operator: '#89DDFF',
    delimiter: '#89DDFF',
    directive: '#73DACA',
    style: { directive: '' },
  },
  editor: {
    selection: '#515C7E4D',
    selectionInactive: '#515C7E25',
    lineHighlight: '#1E202E',
    lineNumber: '#363B54',
    lineNumberActive: '#787C99',
    cursor: '#C0CAF5',
    findMatch: '#3D59A166',
    findMatchHighlight: '#3D59A133',
    indentGuide: '#232433',
    indentGuideActive: '#363B54',
    bracketMatch: '#16161E',
    bracketMatchBorder: '#42465D',
    brackets: ['#698CD6', '#68B3DE', '#9A7ECC', '#25AAC2', '#80A856', '#C49A5A'],
  },
  terminal: {
    foreground: '#A9B1D6',
    selection: '#515C7E4D',
    black: '#363B54',
    red: '#F7768E',
    green: '#73DACA',
    yellow: '#E0AF68',
    blue: '#7AA2F7',
    magenta: '#BB9AF7',
    cyan: '#7DCFFF',
    white: '#787C99',
    brightBlack: '#363B54',
    brightRed: '#F7768E',
    brightGreen: '#73DACA',
    brightYellow: '#E0AF68',
    brightBlue: '#7AA2F7',
    brightMagenta: '#BB9AF7',
    brightCyan: '#7DCFFF',
    brightWhite: '#ACB0D0',
  },
};

export const THEMES: Theme[] = [
  atlas,
  atlasLight,
  auroraLegacy,
  darkModern,
  lightModern,
  dracula,
  gruvboxDark,
  gruvboxLight,
  monokai,
  nord,
  oneDark,
  solarizedDark,
  solarizedLight,
  catppuccinMocha,
  tokyoNight,
];
