//! Os arquivos do projeto do Quartus que o Lace gera para a placa: as
//! configurações (`.qsf`) e os clocks (`.sdc`). Vão para a pasta da placa
//! ([`super::build::build_dir`]), ao lado do topo da placa, e são gravados
//! de novo a cada compilação.
//!
//! O `.qsf` segue o que o próprio Quartus e a Terasic escrevem (pinos por
//! bit, `-to LEDR[0]` sem aspas), e o que o LiteX e o Amaranth geram para
//! as mesmas placas: só o `.qsf`, sem `.qpf`, e os programas do Quartus
//! chamados um por passo. As três linhas dos arquivos de gravação são as que
//! a documentação do openFPGALoader pede: `.rbf` e `.svf` sem compressão,
//! porque pela JTAG a FPGA não descomprime.

use std::fmt::Write as _;

use camino::{Utf8Path, Utf8PathBuf};

use super::config::Resolved;
use super::wrapper::TOP_MODULE;
use crate::error::{LaceError, Result};

/// O nome dos arquivos do projeto (`lace_board_top.qsf`, `.sdc`, `.v`): o do
/// módulo do topo da placa, que é também a revisão do Quartus.
pub const REVISION: &str = TOP_MODULE;

/// A pasta, relativa à da placa, onde o Quartus grava os relatórios e os
/// arquivos de gravação (`PROJECT_OUTPUT_DIRECTORY`).
pub const OUTPUT_DIR: &str = "output_files";

/// O `.qsf`: a FPGA da placa, os arquivos de gravação, os fontes (`sources`,
/// absolutos, na ordem; depois o topo da placa) e os pinos dos sinais que o
/// topo da placa usa, um por bit, com o padrão de I/O de cada um. `root` é a
/// raiz do projeto, onde o Quartus procura um `include`, como o Icarus e o
/// Yosys.
///
/// # Erros
///
/// [`LaceError::InvalidName`] se um caminho tem aspas, `$`, colchetes ou
/// quebra de linha, que o Quartus leria como Tcl.
pub(crate) fn settings(
    resolved: &Resolved,
    sources: &[Utf8PathBuf],
    root: &Utf8Path,
) -> Result<String> {
    let board = &resolved.board;
    let device = &board.device;
    let mut out = String::new();
    let _ = write!(
        out,
        "# Generated by Lace from fpga.json: the Quartus project of the board\n\
         # {} ({}) for the top {}.\n\
         # Lace writes it again on every build: do not edit.\n\n",
        board.name, board.id, resolved.top
    );
    let _ = write!(
        out,
        "set_global_assignment -name FAMILY {}\n\
         set_global_assignment -name DEVICE {}\n\
         set_global_assignment -name TOP_LEVEL_ENTITY {TOP_MODULE}\n\
         set_global_assignment -name PROJECT_OUTPUT_DIRECTORY {OUTPUT_DIR}\n\
         set_global_assignment -name NUM_PARALLEL_PROCESSORS ALL\n\n",
        quoted(&device.family)?,
        device.part
    );
    // O padrão do Quartus (conferido no 25.1), escrito para não depender da
    // versão: um pino sem uso nunca dirige nada que a placa ligue nele.
    out.push_str(
        "# Unused pins: inputs, tri-stated, with the weak pull-up. They never\n\
         # drive what the board connects to them.\n\
         set_global_assignment -name RESERVE_ALL_UNUSED_PINS_WEAK_PULLUP \"AS INPUT TRI-STATED WITH WEAK PULL-UP\"\n\n",
    );
    out.push_str(
        "# Programming files: the .sof for quartus_pgm and, for openFPGALoader,\n\
         # the .rbf and the .svf, uncompressed (the FPGA does not decompress\n\
         # over JTAG).\n\
         set_global_assignment -name ON_CHIP_BITSTREAM_DECOMPRESSION OFF\n\
         set_global_assignment -name GENERATE_RBF_FILE ON\n\
         set_global_assignment -name GENERATE_SVF_FILE ON\n\n",
    );

    out.push_str("# The sources in order, then the board top and the clocks.\n");
    let _ = writeln!(
        out,
        "set_global_assignment -name SEARCH_PATH {}",
        path(root)?
    );
    for file in sources {
        let kind = if file.extension() == Some("sv") {
            "SYSTEMVERILOG_FILE"
        } else {
            "VERILOG_FILE"
        };
        let _ = writeln!(out, "set_global_assignment -name {kind} {}", path(file)?);
    }
    let _ = write!(
        out,
        "set_global_assignment -name VERILOG_FILE {TOP_MODULE}.v\n\
         set_global_assignment -name SDC_FILE {REVISION}.sdc\n\n"
    );

    out.push_str("# The pins of the signals in use, from the board manual.\n");
    let used = resolved
        .board_inputs
        .iter()
        .map(String::as_str)
        .chain(resolved.board_outputs.iter().map(|d| d.signal.as_str()));
    for name in used {
        let Some(signal) = board.signal(name) else {
            continue;
        };
        for (bit, pin) in signal.pins.iter().enumerate() {
            let target = if signal.pins.len() > 1 {
                format!("{name}[{bit}]")
            } else {
                name.to_owned()
            };
            let _ = writeln!(out, "set_location_assignment {pin} -to {target}");
            if let Some(standard) = signal.io_standard.of(bit) {
                let _ = writeln!(
                    out,
                    "set_instance_assignment -name IO_STANDARD {} -to {target}",
                    quoted(standard)?
                );
            }
        }
    }
    Ok(out)
}

/// O `.sdc`: um `create_clock` para cada clock da placa ligado ao topo, com
/// o período do oscilador, e a incerteza que o Quartus deriva sozinho.
pub(crate) fn constraints(resolved: &Resolved) -> String {
    let mut out = String::from(
        "# Generated by Lace from fpga.json: the board clocks connected to the\n\
         # top. Lace writes it again on every build: do not edit.\n\n",
    );
    let mut seen: Vec<&str> = Vec::new();
    for clock in &resolved.clocks {
        if seen.contains(&clock.signal.as_str()) {
            continue;
        }
        seen.push(&clock.signal);
        let _ = writeln!(
            out,
            "create_clock -name {0} -period {1:.3} [get_ports {{{0}}}]",
            clock.signal,
            1000.0 / clock.mhz
        );
    }
    if seen.is_empty() {
        out.push_str("# No board clock is connected to the top.\n");
    }
    out.push_str("derive_clock_uncertainty\n");
    out
}

/// Um texto entre aspas para o `.qsf`.
fn quoted(text: &str) -> Result<String> {
    if text.contains(['"', '$', '[', ']', '\\', '\n', '\r']) {
        return Err(LaceError::InvalidName {
            name: text.to_owned(),
            reason: "Quotes, $, brackets, backslashes and line breaks cannot go into a Quartus settings file".into(),
        });
    }
    Ok(format!("\"{text}\""))
}

/// Um caminho entre aspas para o `.qsf`, com `/`, que o Quartus aceita no
/// Windows.
fn path(path: &Utf8Path) -> Result<String> {
    let native = dunce::simplified(path.as_std_path()).to_string_lossy();
    quoted(&native.replace('\\', "/"))
}

#[cfg(test)]
mod tests {
    use super::super::config::tests::{sapho_top, test_board};
    use super::super::config::{FpgaConfig, Link};
    use super::*;

    fn resolved(links: &[(&str, &str)]) -> Resolved {
        let mut config = FpgaConfig::new("teste");
        config.connect = links.iter().map(|(p, s)| Link::new(*p, *s)).collect();
        config.resolve(&test_board(), &sapho_top()).unwrap()
    }

    #[test]
    fn the_settings_of_a_sapho_processor() {
        let resolved = resolved(&[
            ("clk", "CLOCK_50"),
            ("rst", "!KEY[0]"),
            ("in", "SW"),
            ("out[3:0]", "LED[3:0]"),
            ("out[1:0]", "!HEX0"),
        ]);
        let sources = [
            Utf8PathBuf::from("/opt/lace/yanc/SAPHO/core.v"),
            Utf8PathBuf::from("/p/My Files/proc/Hardware/proc.v"),
            Utf8PathBuf::from("/p/rtl/fifo.sv"),
        ];
        let qsf = settings(&resolved, &sources, Utf8Path::new("/p")).unwrap();
        insta::assert_snapshot!(qsf);
        // Não se sabe em que codificação o Quartus lê: nada fora do ASCII
        // além do que vem do projeto (os caminhos e os nomes).
        let board_top = super::super::wrapper::generate(&resolved);
        for text in [qsf.as_str(), &constraints(&resolved), &board_top] {
            assert!(text.is_ascii(), "{text}");
        }
    }

    #[test]
    fn each_board_clock_once() {
        let sdc = constraints(&resolved(&[("clk", "CLOCK_50"), ("rst", "!KEY[0]")]));
        assert!(
            sdc.contains("create_clock -name CLOCK_50 -period 20.000 [get_ports {CLOCK_50}]\n"),
            "{sdc}"
        );
        assert!(sdc.ends_with("derive_clock_uncertainty\n"));
        assert!(constraints(&resolved(&[("rst", "!KEY[0]")])).contains("No board clock"));
    }

    #[test]
    fn paths_that_tcl_would_read_are_refused() {
        assert_eq!(
            path(Utf8Path::new("/p/My Files/x.v")).unwrap(),
            "\"/p/My Files/x.v\""
        );
        for bad in ["/p/a\"b.v", "/p/$x/a.v", "/p/a[1]/b.v"] {
            assert!(path(Utf8Path::new(bad)).is_err(), "{bad}");
        }
    }
}
