//! O topo da placa: um módulo que tem os sinais da placa como portas e
//! instancia o topo do projeto com as ligações do `fpga.json` ([`Resolved`]).
//!
//! Só os sinais usados viram portas, e só eles recebem pino. As entradas do
//! topo recebem os bits da placa (invertidos com `!`), ou constantes; os bits
//! de um sinal de saída da placa que nada liga ficam no nível inativo (0, ou 1
//! nos ativos em baixo, como os segmentos dos displays).

use super::config::{BitSource, PortBit, Resolved};

/// O nome do módulo gerado.
pub const TOP_MODULE: &str = "lace_board_top";

/// O Verilog do topo da placa.
pub fn generate(resolved: &Resolved) -> String {
    let board = &resolved.board;
    let mut out = String::new();
    // Em inglês e só ASCII, como o .qsf e o .sdc, por precaução: não se
    // sabe em que codificação o Quartus lê os arquivos.
    out.push_str(&format!(
        "// Generated by Lace from fpga.json: the board top of {}, which\n\
         // connects the ports of {} to the board signals.\n\
         // Lace writes it again on every build: do not edit.\n\
         `default_nettype none\n\n",
        board.name, resolved.top
    ));

    // as portas: os sinais usados, as entradas e depois as saídas
    let mut ports = Vec::new();
    for name in &resolved.board_inputs {
        if let Some(signal) = board.signal(name) {
            ports.push(format!("    input  wire {}{name}", range(signal.width())));
        }
    }
    for drive in &resolved.board_outputs {
        ports.push(format!(
            "    output wire {}{}",
            range(drive.bits.len() as u32),
            drive.signal
        ));
    }
    out.push_str(&format!(
        "module {TOP_MODULE} (\n{}\n);\n",
        ports.join(",\n")
    ));

    // um fio por saída do topo
    let outputs: Vec<_> = resolved.ports.iter().filter(|p| !p.input).collect();
    for port in &outputs {
        out.push_str(&format!(
            "    wire {}{};\n",
            range(port.width),
            wire(&port.name)
        ));
    }
    if !outputs.is_empty() {
        out.push('\n');
    }

    // a instância
    let mut connections = Vec::new();
    for port in &resolved.ports {
        let expr = if port.input {
            resolved
                .inputs
                .iter()
                .find(|d| d.port == port.name)
                .map_or_else(
                    || constant(port.width, false),
                    |d| input_expr(resolved, &d.bits),
                )
        } else {
            wire(&port.name)
        };
        connections.push(format!("        .{}({expr})", port.name));
    }
    out.push_str(&format!(
        "    {} u_top (\n{}\n    );\n",
        resolved.top,
        connections.join(",\n")
    ));

    // as saídas da placa
    if !resolved.board_outputs.is_empty() {
        out.push('\n');
    }
    for drive in &resolved.board_outputs {
        out.push_str(&format!(
            "    assign {} = {};\n",
            drive.signal,
            output_expr(resolved, &drive.bits, drive.active_low)
        ));
    }
    out.push_str("endmodule\n\n`default_nettype wire\n");
    out
}

/// Cada ligação como texto, para mostrar: cada entrada do topo com a
/// expressão que a dirige (`rst`, `~KEY[0]`), depois cada sinal de saída da
/// placa usado (`LEDR[17:0]`, `{10'b0, out[7:0]}`). As saídas do topo
/// aparecem pelo nome da porta, sem o prefixo do fio.
pub fn connections(resolved: &Resolved) -> Vec<(String, String)> {
    let mut out = Vec::new();
    for port in resolved.ports.iter().filter(|p| p.input) {
        if let Some(drive) = resolved.inputs.iter().find(|d| d.port == port.name) {
            out.push((
                format!("{}{}", port.name, range(port.width).trim_end()),
                input_expr(resolved, &drive.bits),
            ));
        }
    }
    for drive in &resolved.board_outputs {
        let expr = output_expr(resolved, &drive.bits, drive.active_low).replace("lace_", "");
        out.push((
            format!(
                "{}{}",
                drive.signal,
                range(drive.bits.len() as u32).trim_end()
            ),
            expr,
        ));
    }
    out
}

/// `[7:0] ` para uma largura, nada para um bit.
fn range(width: u32) -> String {
    if width > 1 {
        format!("[{}:0] ", width - 1)
    } else {
        String::new()
    }
}

/// O fio de uma saída do topo.
fn wire(port: &str) -> String {
    format!("lace_{port}")
}

/// `n` bits de um valor fixo.
fn constant(width: u32, value: bool) -> String {
    match (width, value) {
        (_, false) => format!("{width}'b0"),
        (1, true) => "1'b1".to_owned(),
        (_, true) => format!("{{{width}{{1'b1}}}}"),
    }
}

/// Um pedaço de um vetor (ou o nome, se o vetor tem um bit só).
fn slice(name: &str, total: u32, lsb: u32, width: u32) -> String {
    if total == 1 {
        name.to_owned()
    } else if width == 1 {
        format!("{name}[{lsb}]")
    } else {
        format!("{name}[{}:{lsb}]", lsb + width - 1)
    }
}

/// Junta pedaços, do mais alto ao mais baixo, numa concatenação (ou num só).
fn concat(mut parts: Vec<String>) -> String {
    parts.reverse();
    if parts.len() == 1 {
        parts.remove(0)
    } else {
        format!("{{{}}}", parts.join(", "))
    }
}

/// A expressão de uma entrada do topo, com os bits em faixas.
fn input_expr(resolved: &Resolved, bits: &[BitSource]) -> String {
    let mut parts = Vec::new();
    let mut i = 0;
    while i < bits.len() {
        let mut j = i + 1;
        while j < bits.len() && continues(&bits[j - 1], &bits[j]) {
            j += 1;
        }
        let n = (j - i) as u32;
        parts.push(match &bits[i] {
            BitSource::Constant { value } => constant(n, *value),
            BitSource::Pin {
                signal,
                bit,
                invert,
            } => {
                let total = resolved.board.signal(signal).map_or(1, |s| s.width());
                let text = slice(signal, total, *bit, n);
                if *invert { format!("~{text}") } else { text }
            }
        });
        i = j;
    }
    concat(parts)
}

fn continues(prev: &BitSource, next: &BitSource) -> bool {
    match (prev, next) {
        (BitSource::Constant { value: a }, BitSource::Constant { value: b }) => a == b,
        (
            BitSource::Pin {
                signal: s1,
                bit: b1,
                invert: i1,
            },
            BitSource::Pin {
                signal: s2,
                bit: b2,
                invert: i2,
            },
        ) => s1 == s2 && i1 == i2 && *b2 == b1 + 1,
        _ => false,
    }
}

/// A expressão de um sinal de saída da placa, com os bits em faixas.
fn output_expr(resolved: &Resolved, bits: &[Option<PortBit>], active_low: bool) -> String {
    let width_of = |port: &str| {
        resolved
            .ports
            .iter()
            .find(|p| p.name == port)
            .map_or(1, |p| p.width)
    };
    let mut parts = Vec::new();
    let mut i = 0;
    while i < bits.len() {
        let mut j = i + 1;
        while j < bits.len()
            && match (&bits[j - 1], &bits[j]) {
                (None, None) => true,
                (Some(a), Some(b)) => {
                    a.port == b.port && a.invert == b.invert && b.bit == a.bit + 1
                }
                _ => false,
            }
        {
            j += 1;
        }
        let n = (j - i) as u32;
        parts.push(match &bits[i] {
            None => constant(n, active_low),
            Some(first) => {
                let text = slice(&wire(&first.port), width_of(&first.port), first.bit, n);
                if first.invert {
                    format!("~{text}")
                } else {
                    text
                }
            }
        });
        i = j;
    }
    concat(parts)
}

#[cfg(test)]
mod tests {
    use super::super::config::tests::{sapho_top, test_board};
    use super::super::config::{FpgaConfig, Link};
    use super::*;

    fn resolved(links: &[(&str, &str)]) -> Resolved {
        let mut config = FpgaConfig::new("teste");
        config.connect = links.iter().map(|(p, s)| Link::new(*p, *s)).collect();
        config.resolve(&test_board(), &sapho_top()).unwrap()
    }

    #[test]
    fn a_sapho_processor_on_the_board() {
        let verilog = generate(&resolved(&[
            ("clk", "CLOCK_50"),
            ("rst", "!KEY[0]"),
            ("in", "SW"),
            ("out[3:0]", "LED[3:0]"),
            ("out_en", "LED[5]"),
            ("out[1:0]", "!HEX0"),
        ]));
        insta::assert_snapshot!(verilog);
    }

    #[test]
    fn constants_and_inverted_ranges() {
        let verilog = generate(&resolved(&[
            ("clk", "CLOCK_50"),
            ("rst", "0"),
            ("in[15:8]", "1"),
            ("in[1:0]", "!KEY"),
        ]));
        assert!(verilog.contains(".rst(1'b0)"), "{verilog}");
        assert!(
            verilog.contains(".in({{8{1'b1}}, 6'b0, ~KEY[1:0]})"),
            "{verilog}"
        );
        assert!(verilog.contains("    input  wire CLOCK_50,\n"), "{verilog}");
        assert!(!verilog.contains("assign"), "{verilog}");
    }
}
